### ISSUE TITLE
AT S0 Command on older (1.2 and below) versions

### ISSUE THREAD

**Issue by kenrox** [stelian42/HarleyDroid#1]
AT S0 command throws "Error Configuring Elm327" exception in older elm devices.
removing the line\*  from HarleyDroidService.j just helped, even though no spaces are removed (serial data debugged from pc)
- chat("ATS0", "OK", AT_TIMEOUT);

a simple retry on error "STATUS_ERRORAT"
without the ATS0 command cures the issue.

**Comment by stelian42** [comment]
Thanks for the bug report !

I think it would be even better to retrieve the ELM327 version and issue the ATS0 command only for versions > 1.2.

Stelian.

**Comment by stelian42** [comment]
I've put a patch implementing the version test here: http://www.popies.net/tmp/harleydroid-elmversion.patch

I have not tested it because I don't have the setup available right now. Give it a try if you can.

Stelian.

**Comment by kenrox** [comment]
yep that works :D

**Comment by stelian42** [comment]
Thanks for testing, code commited in git.
