### ISSUE TITLE
Req: Millisecs in Log File

### ISSUE THREAD

**Issue by kenrox** [stelian42/HarleyDroid#4]
the absence of millisec's  in log files make combined charting and data analysis a mess in intensive data like rpm.
it would be great to have it for us data-maniacs.. (yep easy peasy, i can code it but this is for the ppl right?  ;))

**Comment by stelian42** [comment]
Isn't this just as simple as:

<pre>
diff --git a/src/org/harleydroid/HarleyDroidLogger.java b/src/org/harleydroid/Ha
index 8c1d8aa..374eff0 100644
--- a/src/org/harleydroid/HarleyDroidLogger.java
+++ b/src/org/harleydroid/HarleyDroidLogger.java
@@ -38,7 +38,7 @@ public class HarleyDroidLogger implements HarleyDataListener
        private static final String TAG = HarleyDroidLogger.class.getSimpleName(
 
        static final SimpleDateFormat TIMESTAMP_FORMAT =
-               new SimpleDateFormat("yyyyMMddHHmmss");
+               new SimpleDateFormat("yyyyMMddHHmmssSSS");
        static {
                TIMESTAMP_FORMAT.setTimeZone(TimeZone.getDefault());
        }
</pre>

**Comment by kenrox** [comment]
yep thats right ;)
