### ISSUE TITLE
Log File Crc Err: Fixed

### ISSUE THREAD

**Issue by kenrox** [stelian42/HarleyDroid#6]
first of all, if you do not have the bluetooth bug. it's impossible to crash harley droid. it's well written.
but for the log files.
a simple routine change will make the files properly record and close it self for analysis.
it's not about harley droid itself crashing but about not closing the files properly.
just add:
path.mkdirs();
            if(mLog!=null)
            {
                mLog.close();
                mLog=null;
            }

the original source.
try {
            File path = new File(Environment.getExternalStorageDirectory(), "/Android/data/org.harleydroid/files/");

```
        path.mkdirs();
```

(in here)
            File logFile = new File(path, "harley-" + TIMESTAMP_FORMAT.format(new Date()) + ".log.gz");
            mLog = new GZIPOutputStream(new FileOutputStream(logFile, false));

problem solved! :D

**Comment by stelian42** [comment]
HarleyDroid's code has changed a lot since this bug report, which is probably not relevant anymore...

Will close the bug when releasing v2.0, which should happen real soon now.
